name: CI

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true

    - name: Create Retail Package
      run: ./utils/packager/release.sh -g retail
      env:
        CF_API_KEY: ${{ secrets.CF_API_KEY }}
        GITHUB_OAUTH: ${{ secrets.GITHUB_TOKEN }}

    - name: Create Classic Package
      run: ./utils/packager/release.sh -g classic
      env:
        CF_API_KEY: ${{ secrets.CF_API_KEY }}
        GITHUB_OAUTH: ${{ secrets.GITHUB_TOKEN }}

    - name: Create Classic Burning Crusade Package
      run: ./utils/packager/release.sh -g bcc
      env:
        CF_API_KEY: ${{ secrets.CF_API_KEY }}
        GITHUB_OAUTH: ${{ secrets.GITHUB_TOKEN }}
